{% set name = "batoid" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04f2f802c0ed31dfca69dca74ccc27a7a19d19637f09f79d571cd9bd137e78f9

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pybind11
    - numpy
    - pytest-runner
  run:
    - python
    - pyyaml
    - {{ pin_compatible('numpy') }}
    - scipy
    - galsim
    - matplotlib-base
    - astropy

test:
  imports:
    - batoid
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jmeyers314/batoid
  summary: 'c++ backed python optical raytracer'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
