{% set name = "batoid" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6feafe1e15e03778debf55fa952e84af7a1f6608a09b2cb0f525250d8a86c67

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pybind11
    - numpy
    - pytest-runner
  run:
    - python
    - pyyaml
    - {{ pin_compatible('numpy') }}
    - scipy
    - galsim
    - matplotlib-base
    - astropy

test:
  imports:
    - batoid
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jmeyers314/batoid
  summary: 'c++ backed python optical raytracer'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
